Repository home-assistant/plugin-audio, pull requests merged in 2022-07, with the labels that each got.

#112 Verbose logging only if in debug mode
  rootfs/etc/services.d/pulseaudio/run
Labels: enhancement, cla-signed

#113 Fix permissions
  rootfs/etc/cont-init.d/alsa-mixer.sh
  rootfs/etc/cont-init.d/filesystem.sh
  rootfs/etc/cont-init.d/pulse-config.sh
  rootfs/etc/fix-attrs.d/scripts
  rootfs/etc/services.d/alsa/run
  rootfs/etc/services.d/pulseaudio/finish
  rootfs/etc/services.d/pulseaudio/run
  rootfs/usr/bin/soundconfig
Labels: cla-signed

#114 `pulse_audio` not `plugin_audio`
  rootfs/etc/services.d/pulseaudio/run
Labels: bug, cla-signed

#115 Audio mounts to /data not /config
  rootfs/etc/services.d/pulseaudio/run
Labels: bug, cla-signed

#116 Restructure configuration apply
  rootfs/etc/services.d/pulseaudio/run
Labels: cla-signed

#117 Fix bashio commands
  rootfs/etc/services.d/pulseaudio/run
Labels: cla-signed
